name: MATRIX DEMO
on: work_dispatch
jobs:
  Build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14,16]
        operating-systm: [ubuntu-latest, windows-latest]
        include: 
          - node-version: 22
            operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
        